# Generated by Django 2.1.3 on 2018-11-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='person',
            field=models.CharField(choices=[('dppc', 'dppc'), ('student', 'student'), ('staff', 'staff'), ('hod', 'hod'), ('faculty', 'faculty')], default='student', max_length=100),
        ),
    ]
