# Generated by Django 2.1.3 on 2018-11-02 09:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeaveFrom', models.DateField()),
                ('LeaveTo', models.DateField()),
                ('TypeOfLeave', models.CharField(choices=[('Ordinary', 'Ordinary'), ('Medical', 'Medical'), ('Acedemic', 'Acedemic'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity')], default='', max_length=255)),
                ('ReasonForLeave', models.CharField(max_length=200)),
                ('Doc1', models.FileField(blank=True, null=True, upload_to='documents')),
                ('Doc2', models.FileField(blank=True, null=True, upload_to='documents')),
                ('AddressWhileOnLeave', models.CharField(max_length=200)),
                ('PhoneNumberWhileOnLeave', models.CharField(max_length=20)),
                ('DateOfApply', models.DateField(default=datetime.datetime.now)),
                ('Flag', models.IntegerField(default=0)),
                ('SentTo', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Supervisor'), ('2', 'TAinstructor'), ('3', 'DPPC')], max_length=5)),
                ('ApprovedStatus', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined')], default='pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remark', models.CharField(max_length=200)),
                ('Person', models.CharField(max_length=40)),
                ('DateOfComment', models.DateField(default=datetime.datetime.now)),
                ('Leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leave_portal.ApplyLeave')),
            ],
        ),
        migrations.CreateModel(
            name='Dppc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, default=' ', null=True, upload_to='faculty')),
                ('webmail', models.CharField(max_length=128)),
                ('mob_num', models.CharField(max_length=128)),
                ('dppc_id', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dpppc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, default=' ', null=True, upload_to='faculty')),
                ('webmail', models.CharField(max_length=128)),
                ('mob_num', models.CharField(max_length=128)),
                ('faculty_id', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, default=' ', null=True, upload_to='faculty')),
                ('webmail', models.CharField(max_length=128)),
                ('mob_num', models.CharField(max_length=128)),
                ('hod_id', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, default=' ', null=True, upload_to='faculty')),
                ('webmail', models.CharField(max_length=128)),
                ('mob_num', models.CharField(max_length=128)),
                ('staff_id', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='student')),
                ('roll_no', models.CharField(default=' ', max_length=128, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('webmail', models.CharField(max_length=128, unique=True)),
                ('course', models.CharField(blank=True, choices=[('Mtech', 'Mtech'), ('Phd', 'Phd'), ('NA', 'NA')], max_length=128)),
                ('acedemic_year', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0)),
                ('present_semester', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True)),
                ('hostel_name', models.CharField(blank=True, choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('Married_Scholar', 'Married_Scholar'), ('NA', 'NA')], default='', max_length=255)),
                ('room_number', models.CharField(blank=True, default='', max_length=10)),
                ('mob_number', models.CharField(default=' ', max_length=15)),
                ('emergency_mob_num', models.CharField(blank=True, default=' ', max_length=15)),
                ('TA_instructor', models.CharField(blank=True, default='', max_length=200)),
                ('Supervisor_1', models.CharField(blank=True, default='', max_length=200)),
                ('Ordinary', models.IntegerField(default=15)),
                ('Medical', models.IntegerField(default=15)),
                ('Acedemic', models.IntegerField(default=30)),
                ('Maternity', models.IntegerField(default=135)),
                ('Paternity', models.IntegerField(default=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['roll_no'],
            },
        ),
        migrations.AddField(
            model_name='applyleave',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyleaves', to='leave_portal.Student'),
        ),
    ]
