# Generated by Django 2.1.3 on 2018-11-04 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Supervisor_1',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='Supervisor', to='leave_portal.Faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='TA_instructor',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='TA', to='leave_portal.Faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30),
        ),
    ]
