# Generated by Django 2.1.4 on 2019-03-13 22:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leave_portal', '0003_auto_20181104_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='TASlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingMonth', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=100)),
                ('endingMonth', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=100)),
                ('flag', models.IntegerField(default=0)),
                ('SentTo', multiselectfield.db.fields.MultiSelectField(choices=[('2', 'Supervisor'), ('1', 'TAinstructor')], max_length=3)),
                ('ApprovedStatus', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined')], default='pending', max_length=100)),
                ('DateOfApply', models.DateField(default=datetime.datetime.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taSlip', to='leave_portal.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='applyleave',
            name='SentTo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('2', 'Supervisor'), ('1', 'TAinstructor'), ('3', 'DPPC')], max_length=5),
        ),
    ]
