# Generated by Django 2.1.7 on 2019-03-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_portal', '0005_remove_taslip_sentto'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Ordinary1',
            field=models.IntegerField(default=15),
        ),
    ]
